name: Feature Branch
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  default:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@main
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
