name: Main Branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@main
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
